---
title: "3. STAC formatting"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{3. STAC formatting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Labels provided for the STAC machine learning catalogs are sourced from two 'locations'. First, there are the raw labels as assigned by agronomists to two seasons of images acquired during the EotG project. Second, there are the labels generated using machine learning algorithms based upon the first set for the remainder of the data provided. 

Data screening of initial labels (and hence model results) shows some very small images which are generally ignored and not included in the final dataset. After screening we retained ~17K images.

Labels are provided for instances of:

- Growth stages
  - sowing to germination
  - early to late vegetative growth
  - flowering
  - early to late maturity

- rainfall damage
  - drought
  - no damage
  - excess rainfall

- extent of damage
  - a percentage

Ancillary data are provided as zipped json files. Ancillary data is not image specific and covers the whole season associated with an image.

## STAC structure

A visual preview of the github hosted STAC catolog can be found here:

https://radiantearth.github.io/stac-browser/#/external/raw.githubusercontent.com/khufkens/EotG_data/main/release_v1/catalog.json

These data are cleared for use, however we forsee further integration in the Radiant Earth Machine Learning hub (MLhub), data will migrate there once full compliance is assured with the Radiant Earth in house STAC specifications.